//
//  Classification.swift
//  2023BIFF
//
//  Created by GYURI PARK on 2023/09/18.
//

import Foundation

class Classification: Identifiable {
    let id: Int
    @Published var title: String
    @Published var description: String
    @Published var movieTitle: [String]
    @Published var movieEng: [String]
    @Published var directorNm: [String]
    @Published var directorEng: [String]
    @Published var runningTime: [Int]
    
    init(id: Int, title: String, description: String, movieTitle: [String], movieEng: [String], directorNm: [String], directorEng: [String], runningTime: [Int]) {
        self.id = id
        self.title = title
        self.description = description
        self.movieTitle = movieTitle
        self.movieEng = movieEng
        self.directorNm = directorNm
        self.directorEng = directorEng
        self.runningTime = runningTime
    }
}

class ClassificationList {
    static let classifications: [Classification] = [
        Classification(id: 1,
                       title: "개막작",
                       description: "2023 부산국제영화제 개막작",
                       movieTitle: ["한국이 싫어서"],
                       movieEng: ["Because I Hate Korea"],
                       directorNm: ["장건재"],
                       directorEng: ["JANG Kun-jae"],
                       runningTime: [106]),
        Classification(id: 2,
                       title: "폐막작",
                       description: "2023 부산국제영화제 페막작",
                       movieTitle: ["영화의 황제"],
                       movieEng: ["The Movie Emperor"],
                       directorNm: ["닝하오"],
                       directorEng: ["NING Hao"],
                       runningTime: [125]),
        Classification(id: 3,
                       title: "갈라 프레젠테이션",
                       description: "거장 감독의 신작 또는 세계적으로 주목 받는 화제작 가운데 감독이나 배우가 영화를 직접 소개하고 관객과의 만남을 갖는 섹션",
                       movieTitle: ["괴물", "녹야", "더 비스트"],
                       movieEng: ["Monster", "Green Night", "The Beast"],
                       directorNm: ["고레에다 히로카즈", "한슈아이", "베르트랑 보넬로"],
                       directorEng: ["KORE-EDA Hirokazu", "HAN Shuai", "Bertrand BONELLO"],
                       runningTime: [126, 92, 146]),
        Classification(id: 4,
                       title: "아이콘",
                       description: "동시대를 대표하는 거장들의 신작을 소개하는 섹션",
                       movieTitle: ["가여운 것들", "공드리의 솔루션북", "나의 올드 오크", "납치", "더 킬러", "라스트 썸머", "마른 풀에 관하여", "메뉴의 즐거움 - 트와그로 가족", "물안에서", "뮤직", "바튼 아카데미", "백탑지광", "북두칠성", "빔 벤더스의 안젤름 3D", "악은 존재하지 않는다", "엘레지", "우리의 하루", "유레카", "유령들의 초상", "지구 종말이 오더라도 너무 큰 기대는 말라", "찬란한 내일로", "청춘(봄)", "추락의 해부", "클로즈 유어 아이즈", "키메라", "파리 아다망에서 만난 사람들", "폴른 리브스", "푸른 장벽", "프렌치 수프", "호수의 깊은 진실"],
                       movieEng: ["Poor Things", "The Book of Solutions", "The Old Oak", "Kidnapped", "The Killer", "Last Summer", "About Dry Grasses", "Menus Plaisirs - Les Troisgros", "IN WATER", "Music", "The Holdovers", "The Shadowless Tower", "The Plough", "Anselm", "Evil Does Not Exist", "Elegies", "IN OUR DAY", "Eureka", "Pictures of Ghosts", "Do Not Expect Too Much from the End of the World", "A Brighter Tomorrow", "Youth(Spring)", "Anatomy of a Fall", "Close Your Eyes", "La Chimera", "On the Adamant", "Fallen Leaves", "Green Border", "The Pot-au-Feu", "Essential Truths of the Lake"],
                       directorNm: ["요르고스 란티모스", "미셸 공드리", "켄 로치", "마르코 벨로키오", "데이빗 핀처", "카트린느 브레야", "누리 빌게 제일란", "프레데릭 와이즈먼", "홍상수", "앙겔라 샤넬렉", "알렉산더 페인", "장률", "필립 가렐", "빔 벤더스", "하마구치 류스케", "허안화", "홍상수", "리산드로 알론조", "클레버 멘도사 필루", "라두 주데", "난니 모레티", "왕빙", "쥐스틴 트리에", "빅토르 에리세", "알리체 로바허", "니콜라 필리베르", "아키 카우리스마키", "아그네츠카 홀란드", "트란 안 홍", "라브 디아즈"],
                       directorEng: ["Yorgos LANTHIMOS", "Michel GONDRY", "Ken LOACH", "Marco BELLOCCHIO", "David FINCHER", "Catherine BREILLAT", "Nuri BILGE CEYLAN", "Frederick WISEMAN", "HONG Sangsoo", "Angela SCHANELEC", "Alexander PAYNE", "ZHANG Lu", "Philippe GARREL", "Wim WENDERS", " HAMAGUCHI Ryusuke", "Ann HUI", "HONG Sangsoo", "Lisandro ALONSO", "Kleber MENDONÇA FILHO", "Radu JUDE", "Nanni MORETTI", "WANG Bing", "Justine TRIET", "Víctor ERICE", "Alice ROHRWACHER", "Nicolas PHILIBERT", "Aki KAURISMÄKI","Agnieszka HOLLAND", "TRAN Anh Hung", "Lav DIAZ"],
                       runningTime: [141, 102, 113, 134, 113, 103, 197, 240, 61, 108, 133, 144, 95, 94, 106, 102, 83, 146, 93, 163, 95, 215, 150, 169, 132, 109, 81, 152, 135, 215]),
        Classification(id: 5,
                       title: "지석",
                       description: "세 편 이상의 장편영화를 만든 아시아 중견 감독의 신작 경쟁 부문",
                       movieTitle: ["가스퍼의 24시간", "그녀에게", "달", "도이 보이", "모로", "신부 납치", "이 영화의 끝에서", "이치코", "자서전 비슷한 것", "파라다이스"],
                       movieEng: ["24 Hours with Gaspar", "Blesser", "The Moon", "Doi Boy", "Moro", "Bride Kidnapping", "At the End of the Flim", "Ichiko", "Something Like an Autobiography", "Paradise"],
                       directorNm: ["요셉 앙기 노엔", "이상철", "이시이 유야", "논타왓 눔벤차폰", "브리얀테 멘도사", "미를란 압디칼리코프", "안선경", "도다 아키히로", "모스토파 사르와르 파루키", "프라사나 비타나게"],
                       directorEng: ["Yosep Anggi NOEN", "LEE Sangcheol", "ISHII Yuya", "Nontawat NUMBENCHAPOL", "Brillante MENDOZA", "Mirlan ABDYKALYKOV", "AHN Sunkyoung", "TODA Akihiro", "Mostofa Sarwar FAROOKI", "Prasanna VITHANAGE"],
                       runningTime: [98, 105, 144, 99, 80, 80, 175, 125, 82, 93]),
        Classification(id: 6,
                       title: "아시아영화의 창",
                       description: "아시아의 중견감독들과 신인감독들의 다양한 시각과 스타일을 엿볼 수 있는 신작 및 화제작을 소개하는 섹션",
                       movieTitle: ["10년: 미얀마", "강변의 착오", "꿈꾸는 청소부", "나의 딸, 조람", "내 사랑 샐리", "노란 누에고치 껌데기 속", "뒷골목의 알리 토판", "로테섬의 여인들", "마을로 가는 길", "모든 밤을 기억하다", "모리슨", "바람의 도시", "불꽃 속으로", "블루 송", "사라의 수난", "소녀 구라스", "소년과 소녀", "소리를 따라가다", "속삭이는 산", "스크림", "아그라", "안개 너머", "인샬라 어 보이", "일초 앞, 일초 뒤", "차라리 겨울 잠을 자고 싶어", "총을 든 스님", "크리티컬 존", "키리에의 노래", "파문", "황홀경"],
                       movieEng: ["Ten Years Myanmar", "Only the River Flows", "The Scavenger of Dreams", "Joram", "Salli", "Inside the Yellow Cocoon Shell", "Ali Topan", "Women from Rote Island", "A Road to A Village", "Remembering Every Night", "Morrison", "City of Wind", "In Flames", "A Song Sung Blue", "Sara", "Guras", "A Boy and A Girl", "Following the Sound", "Whispering Mountains", "Scream", "Agra", "Beyond the Fog", "Inshallah a Boy", "One Second Ahead, One Second Behind", "If Only I Could Hibernate", "The Monk and the Gun", "Critical Zone", "KYRIE", "Ripples", "Rapture"],
                       directorNm: ["따잇디, 네운 니, 미요따 케, 아웅 민, 라메 우", "웨이슈준", "수만 고쉬", "데바쉬시 마키자", "리엔치엔홍", "팜 티엔 안", "싯다르타 타타", "제레미아스 냥운", "나빈 수바", "기요하라 유이", "푸티퐁 아룬펭", "퓨레브-오기어 카비주램", "자랄 칸", "겅즈한", "이스마일 바스베스", "사우라브 레이", "쉬리다", "스기타 교시", "자가스 마누와르나", "켄제벡 샤이카코프", "카누 벨", "무라세 다이치", "아마드 알 라쉬드", "야마시타 노부히로", "푸레브다쉬 졸자르갈", "파오 초이닝 도르지", "알리 아마드자데", "이와이 슌지", "오기가미 나오코", "도미닉 상마"],
                       directorEng: ["Thaiddhi, Nay Wunn NI, Myo Thar KHIN, Aung MIN, Lamin OO", "WEI Shujun", "Suman GHOSH", "Devashish MAKHIJA", "LIEN Chien-Hung", "PHAM THIEN An", "Sidharta TATA", "Jeremias NYANGOEN", "Nabin SUBBA", "KIYOHARA Yui", "Phuttiphong AROONPHENG", "PUREV-OCHIR Lkhagvadulam", "Zarrar KAHN", "GENG Zihan", "Ismail BASBETH", "Saurav RAI", "HSU Li-Da", "SUGITA Kyoshi", "Jagath MANUWARNA", "Kenzhebek SHAIKAKOV", "Kanu BEHL", "MURASE Daichi", "Amjad AL RASHEED", "YAMASHITA Nobuhiro", "PUREVDASH Zoljargal", "Pawo Choyning DORJI", "Ali AHMADZADEH", "IWAI Shunji", "OGIGAMI Naoko", "Dominic SANGMA"],
                       runningTime: [104, 101, 85, 138, 106, 179, 114, 106, 106, 116, 106, 103, 98, 92, 99, 114, 140, 84, 86, 108,  132, 83, 113, 119, 99, 107, 99, 178, 120, 127]),
        Classification(id: 7,
                       title: "뉴 커런츠",
                       description: "아시아 영화의 미래를 이끌 신인 감독들의 첫 번째 또는 두 번째 장편 경쟁 부문",
                       movieTitle: ["1923년 9월", "그 여름날의 거짓말", "더 레슬러", "부모 바보", "빌려온 시간", "솔리드 바이 더 씨", "스트레인저", "스파크", "열병을 앓고 난 뒤", "지금, 오아시스"],
                       movieEng: ["SEPTEMBER 1923", "That Summer′s Lie", "The Wrestler", "Heritage", "Borrowed Time", "Solids by the Seashore", "The Stranger", "The Spark", "After the Fever", "Oasis of Now"],
                       directorNm: ["모리 다츠야", "손현록", "이퀴발 초두리", "이종수", "초이지", "파티판 분타릭", "비플랍 사르카", "라제쉬 잘라", "야마모토 아키라", "치아 치섬"],
                       directorEng: ["MORI Tatsuya", "SOHN Hyun-lok", "Iqbal H. CHOWDHURY", "LEE Jong-su", "CHOY Ji", "Patiparn BOONTARIG", "Biplob SARKAR", "Rajesh S. JALA", "YAMAMOTO Akira", "CHIA Chee Sum"],
                       runningTime: [137, 138, 92, 101, 93, 93, 80, 98, 127, 90]),
        Classification(id: 8,
                       title: "한국영화의 오늘 - 스페셜프리미어",
                       description: "특별한 대중적 매력과 위상을 지닌 동시대 한국 주류 상업 영화의 최신작 및 대표작을 프리미어로 상영하는 섹션",
                       movieTitle: ["독전 2", "발레리나", "화란"],
                       movieEng: ["Believer 2", "Ballerina", "Hopeless"],
                       directorNm: ["백감독", "이충현", "김창훈"],
                       directorEng: ["BAIK", "LEE Chung-hyun", "KIM Chang-hoon"],
                       runningTime: [115, 93, 124]),
        Classification(id: 9,
                       title: "한국영화의 오늘 - 파노라마",
                       description: "동시대 한국영화의 역량과 흐름을 만끽할 수 있는 그해의 다양한 대표작 및 최신작을 선보이는 섹션",
                       movieTitle: ["괜찮아 괜찮아 괜찮아!", "달짝지근해: 7510", "보호자", "비공식작전", "세기말의 사랑", "소울메이트", "소풍"],
                       movieEng: ["IT′S OKAY!", "Honeysweet", "A Man of Reason", "Ransomed", "Ms. Apocalypse", "Soulmate", "Picnic"],
                       directorNm: ["김혜영", "이한", "정우성", "김성훈", "임선애", "민용근", "김용균"],
                       directorEng: ["KIM Hyeyoung", "LEE Han", "JUNG Woosung", "KIM Seong-hun", "LIM Sun-ae", "MIN Yong-keun", "KIM Yong-gyun"],
                       runningTime: [102, 119, 97, 132, 116, 124, 120]),
        Classification(id: 10,
                       title: "한국영화의 오늘 - 비전",
                       description: "뛰어난 작품성과 독창적 비전을 지닌 한국독립영화 최신작을 선보이는 섹션",
                       movieTitle: ["301호 모텔 살인사건", "딜리버리", "딸에 대하여", "막걸리가 알려줄거야", "바얌섬", "소리굴다리", "장손", "지난 여름", "한 채", "해야 할 일"],
                       movieEng: ["The Guest", "Delivery", "Concerning My Daughter", "FAQ", "Isle of Snakes", "Sorigouldari: The Sound Underpass", "House of the Seasons", "Last Summer", "The Berefts", "Work to Do"],
                       directorNm: ["연제광", "장민준", "이미랑", "김다민", "김유민", "구파수 륜호이", "오정민", "최승우", "정범, 허장", "박홍준"],
                       directorEng: ["YEON Jegwang", "JANG Min-joon", "LEE Mirang", "KIM Da-min", "Eu-min KIM", "GUPASU Ryunhoi", "OH Jung-min", "CHOI Seung-woo", "Jeong Beom, HUR Jang", "PARK Hong-jun"],
                       runningTime: [77, 102, 106, 92, 115, 67, 121, 76, 89, 103]),
        Classification(id: 11,
                       title: "월드 시네마",
                       description: "비아시아권 중견 작가들과 신인 감독들의 신작 및 유수 국제영화제 수상작을 포함하여 한 해 세계 영화의 전체적인 흐름을 조망할 수 있는 섹션",
                       movieTitle: ["가족의 탄생", "더 골드만 케이스", "더 킹 타이드", "레드 룸스", "마거리트의 정리", "마침내 새벽", "모든 것의 설명", "본인 출연, 제리", "블라가의 마지막 수업", "블랙버드 블랙버드 블랙베리", "비행자들", "빈센트 머스트 다이", "아다지오", "아모레의 마지막 밤", "알레마니아", "약속의 땅", "우먼 오브", "클럽 제로", "티처스 라운지", "하늘을 나는 아빠를 보았다", "홀리", "히어"],
                       movieEng: ["Housekeeping for Beginners", "The Goldman Case", "The King Tide", "Red Rooms", "Marguerite′s Theorem", "Finally Dawn", "Explanation for Everything", "Starring Jerry as Himself", "Blaga′s Lessons", "Blackbird Blackbird Blackberry", "The Delinquents", "Vincent Must Die", "Adagio", "The Last Night of Amore", "Alemania", "The Promised Land", "Woman of...", "Club Zero", "The Teachers′ Lounge", "Behind the Mountains", "Holly", "Here"],
                       directorNm: ["고란 스톨레프스키", "세드릭 칸", "크리스찬 스팍스", "파스칼 플란테", "안나 노비옹", "사베리오 코스탄초", "가보르 레이츠", "라우 첸", "스테판 코만다레프", "엘레네 나베리아니", "로드리고 모레노", "스테판 카스탕", "스테파노 솔리마", "안드레아 디 스테파노", "마리아 자네티", "니콜라이 아르셀", "마우고시카 슈모프스카, 미할 엔그레르트", "예시카 하우스너", "일커 차탁", "모하메드 벤 아티야", "핀 트로흐", "바스 데보스"],
                       directorEng: ["Goran STOLEVSKI", "Cédric KAHN", "Christian SPARKES", "Pascal PLANTE", "Anna NOVION", "Saverio COSTANZO", "Gábor REISZ", "Law CHEN", "Stephan KOMANDAREV", "Elene NAVERIANI", "Rodrigo MORENO", "Stéphan CASTANG", "Stefano SOLLIMA", "Andrea DI STEFANO", "María ZANETTI", "Nikolaj ARCEL", "Małgorzata SZUMOWSKA, Michał ENGLERT", "Jessica HAUSNER", "İlker ÇATAK", "Mohamed BEN ATTIA", "Fien TROCH", "Bas DEVOS"],
                       runningTime: [107, 116, 104, 118, 112, 142, 152, 75, 114, 110, 189, 108, 127, 125, 87, 127, 131, 110, 99, 98, 102, 82]),
        Classification(id: 12,
                       title: "플래시 포워드",
                       description: "독창적인 영화 세계를 선보인 비아시아권 신인 감독들의 첫 번째 혹은 두 번째 장편을 소개하는 부문",
                       movieTitle: ["끝없는 일요일", "더 드리머", "립세의 사계", "사라진 소년병", "셰이다", "하늘을 달려", "하우 투 해브 섹스", "호밀의 뿔"],
                       movieEng: ["An Endless Sunday", "The Dreamer", "The Peasants", "The Vanishing Soldier", "Shayda", "Upon Open Sky", "How to Have Sex", "The Rye Horn"],
                       directorNm: ["알랭 파로니", "아나이스 뗄렌느", "DK 웰치먼, 휴 웰치먼", "대니 로젠버그", "누라 니아사리", "마리아나 아리아가, 산티아고 아리아가", "몰리 매닝 워커", "하이오네 캄보르다"],
                       directorEng: ["Alain PARRONI", "Anaïs TELLENNE", "DK WELCHMAN, Hugh WELCHMAN", "Dani ROSENBERG", "Noora NIASARI", "Mariana ARRIAGA, Santiago ARRIAGA", "Molly MANNING WALKER", "Jaione CAMBORDA"],
                       runningTime: [115, 94, 114, 98, 118, 117, 98, 105]),
        Classification(id: 13,
                       title: "와이드 앵글 - 한국 단편 경쟁",
                       description: "영화의 시선을 넓혀 색다르고 차별화된 비전을 보여주는 단편영화와 다큐멘터리를 모아 선보이는 섹션",
                       movieTitle: ["8월의 크리스마스", "덕희는 ㅇㅇ이 있다", "마이디어", "물고기 소년", "샐리", "업보", "인공 세상의 새로운 아침", "자매의 맛", "초면에 발생한 분쟁을 조정하는 세 가지 질문", "홈"],
                       movieEng: ["Christmas in Summer", "She Wants True Love", "MYDEAR", "Fisher Boy", "Sally", "KARMA", "New Morning of an Artificial World", "Flavor of Sisterhood", "Three Questions That Lead to Love", "Home"],
                       directorNm: ["이가홍", "염민정", "전도희, 김소희", "남동현", "이정주", "최수혁", "송진욱", "황인원", "은고", "이혜빈"],
                       directorEng: ["LEE Gahong", "YEOM On", "JEON Dohee, KIM Sohee", "NAM Dong-hyun", "LEE Jeong-joo", "CHOI Soohyuk", "SONG Jinwook", "HWANG Inwon", "Eun-grace KO", "LEE Hyebin"],
                       runningTime: [30, 30, 25, 25, 26, 20, 22, 26, 15, 23]),
        Classification(id: 14,
                       title: "와이드 앵글 - 아시아 단편 경쟁",
                       description: "영화의 시선을 넓혀 색다르고 차별화된 비전을 보여주는 단편영화와 다큐멘터리를 모아 선보이는 섹션",
                       movieTitle: ["21주 후", "나의 여름을 돌려줘", "누구나 때로는 사랑이 필요하니까", "롤러코스터", "뿌리 없는 꽃", "양 양 양", "얼굴 없는 마부", "증인 나무"],
                       movieEng: ["21 Weeks Later", "Reclaim My Summer", "Everybody’s Gotta Love Sometimes", "Roller Coaster", "The Rootless Bloom", "Lamb Lamb Lamb", "Headless Horsemen", "The Witness Tree"],
                       directorNm: ["나스린 모하마드퍼", "첸하오웨이", "세인 라이언 툰", "첸신얀, 장징천", "레인 메이첼슨", "송동슈", "오브사나 게보르얀", "니란잔 라즈 비일"],
                       directorEng: ["Nasrin MOHAMMADPOUR", "CHEN Hao-wei", "Sein LYAN TUN", "CHEN Xinyan, ZHANG Jingchen", "Rein MAYCHAELSON", "SONG Dongxu", "Ovsanna GEVORGYAN", "Niranjan Raj BHETWAL"],
                       runningTime: [14, 29, 15, 21, 15, 14, 16, 15]),
        Classification(id: 15,
                       title: "와이드 앵글 - 다큐멘터리 경쟁",
                       description: "영화의 시선을 넓혀 색다르고 차별화된 비전을 보여주는 단편영화와 다큐멘터리를 모아 선보이는 섹션",
                       movieTitle: ["그날의 딸들", "깜빡이는 불빛", "되살아나는 목소리", "먼지가 되느니 재가 되리", "여공의 밤", "올빼미, 정원 그리고 작가", "우리들의 공화국", "청년정치백서-쇼미더저스티스"],
                       movieEng: ["The Daughters of That Day", "Flickering Lights", "The Voices of the Silenced", "Rather be Ashes Than Dust", "The Night of the Factory Girls", "An Owl, A Garden &amp; The Writer", "Republic", "SHOW ME THE JUSTICE"],
                       directorNm: ["고훈", "아누파마 스리니바산, 아니르반 두타", "박수남, 박마의", "알란 라우", "김건희", "사라 다우라타바디", "진지앙", "이일하"],
                       directorEng: ["KOH Hoon", "Anupama SRINIVASAN, Anirban DUTTA", "PARK Soo-nam, PARK Maeui", "Alan LAU", "KIM Geonhee", "Sara DOLATABADI", "JIN Jiang", "LEE Ilha"],
                       runningTime: [94, 90, 137, 114, 100, 83, 107, 99]),
        Classification(id: 16,
                       title: "와이드 앵글 - 다큐멘터리 쇼케이스",
                       description: "영화의 시선을 넓혀 색다르고 차별화된 비전을 보여주는 단편영화와 다큐멘터리를 모아 선보이는 섹션",
                       movieTitle: ["강가에서", "그 모든 거짓말의 어머니", "노란문: 세기말 시네필 다이어리", "비욘드 유토피아", "아프간 리스트", "약속", "워터컬러스", "조류를 거슬러", "진리에게", "키스 더 퓨처", "키아로스타미는 작업 중", "판타스틱 머신", "포 도터스"],
                       movieEng: ["Talking with Rivers", "The Mother of All Lies", "Yellow Door: ′90s Lo-fi Film Club", "Beyond Utopia", "The List", "Promise", "Watercolors", "Against the Tide", "Dear Jinri", "Kiss the Future", "Kiarostami at Work", "And the King Said, What a Fantastic Machine", "Four Daughters"],
                       directorNm: ["모흐센 마흐말바프", "아스마에 엘 무디르", "이혁래", "마들렌 가빈", "하나 마흐말바프", "민병훈", "이인훈, 김남석, 김현수", "사르브닉 카우르", "정윤석", "네나드 치친-사인", "세이폴라 사마디안", "악셀 다니엘손, 막시밀리언 반 아에르트릭크", "카우테르 벤 하니아"],
                       directorEng: ["Mohsen MAKHMALBAF", "Asmae EL MOUDIR", "LEE Hyuk-rae", "Madeleine GAVIN", "Hana MAKHMALBAF", "MIN Byung-hun", "LEE Inhoon, KIM Namsuk, KIM Hyunsoo", "Sarvnik KAUR", "JUNG Yoonsuk", "Nenad CICIN-SAIN", "Seifollah SAMADIAN", "Axel DANIELSON, Maximilien VAN AERTRYCK", "Kaouther BEN HANIA"],
                       runningTime: [50, 96, 84, 115, 65, 84, 88, 97, 101, 103, 76, 88, 107]),
        Classification(id: 17,
                       title: "오픈 시네마",
                       description: "작품성과 대중성을 겸비한 신작 및 국제적인 관심을 모은 화제작을 영화의전당 야외극장에서 상영",
                       movieTitle: ["도그맨", "리볼버 릴리", "발리우드 러브스토리", "애니멀 킹덤", "영웅본색 (4K 복원작)", "원 모어 찬스"],
                       movieEng: ["Dogman", "Revolver Lily", "Rocky and Rani′s Love Story", "The Animal Kingdom", "A Better Tomorrow (4K Restoration)", "One More Chance"],
                       directorNm: ["뤽 베송", "유키사다 이사오", "카란 조하르", "토마스 카일리", "오우삼", "앤소니 펀"],
                       directorEng: ["Luc BESSON", "YUKISADA Isao", "Karan JOHAR", "Thomas CAILLEY", "John WOO", "Anthony PUN"],
                       runningTime: [114, 138, 169, 128, 95, 115]),
        Classification(id: 18,
                       title: "미드나잇 패션",
                       description: "작품성과 오락성을 겸비한 호러, 사이언스 픽션, 컬트영화를 신작 위주로 소개하는 부문",
                       movieTitle: ["괴물", "녹야", "더 비스트"],
                       movieEng: ["Monster", "Green Night", "The Beast"],
                       directorNm: ["고레에다 히로카즈", "한슈아이", "베르트랑 보넬로"],
                       directorEng: ["KORE-EDA Hirokazu", "HAN Shuai", "Bertrand BONELLO"],
                       runningTime: [126, 92, 146]),
        Classification(id: 19,
                       title: "온 스크린",
                       description: "영화의 확장된 흐름과 가치를 포괄하는, 그 해 최신의 드라마 시리즈 화제작을 상영하는 부문",
                       movieTitle: ["데드랜드", "레이징 그레이스", "탄생/재탄생", "파툼"],
                       movieEng: ["Deadland", "Raging Grace", "Birth/Rebirth", "Fatum"],
                       directorNm: ["랜스 라슨", "패리스 자실라", "로라 모스", "후안 갈리냐네스"],
                       directorEng: ["Lance LARSON", "Paris ZARCILLA", "Laura MOSS", "Juan GALIÑANES"],
                       runningTime: [91, 100, 100, 92]),
        Classification(id: 20,
                       title: "특별기획 프로그램 Ⅰ - 주윤발의 영웅본색 周潤發之英雄風範",
                       description: "‘주윤발의 영웅본색’에서는 주윤발 배우의 대표작 두 편과 올해의 신작을 포함하여, 총 세 편의 영화를 상영",
                       movieTitle: ["영웅본색 (4K 복원작)", "와호장룡 (4K 복원작)", "원 모어 찬스"],
                       movieEng: ["A Better Tomorrow (4K Restoration)", "Crouching Tiger, Hidden Dragon (4K Restoration)", "One More Chance"],
                       directorNm: ["오우삼", "이안", "앤소니 펀"],
                       directorEng: ["John WOO", "Ang LEE", "Anthony PUN"],
                       runningTime: [95, 120, 115]),
        Classification(id: 21,
                       title: "특별기획 프로그램 Ⅱ - 코리안 아메리칸 특별전: 코리안 디아스포라",
                       description: "올해 특별기획 프로그램 Ⅱ은 ‘코리안 아메리칸 특별전: 코리안 디아스포라’다.",
                       movieTitle: ["미나리", "버닝", "서치", "자모자야", "콜럼버스", "패스트 라이브즈"],
                       movieEng: ["Minari", "Burning", "Searching", "Jamojaya", "Columbus", "Past Lives"],
                       directorNm: ["정이삭", "이창동", "아니쉬 차간티", "저스틴 전", "코고나다", "셀린 송"],
                       directorEng: ["Lee Isaac CHUNG", "LEE Chang-dong", "Aneesh CHAGANTY", "Justin CHON", "Kogonada", "Celine SONG"],
                       runningTime: [115, 148, 102, 93, 104, 105]),
        Classification(id: 22,
                       title: "특별기획 프로그램 Ⅲ - 인도네시아 영화의 르네상스",
                       description: "올해 특별기획 프로그램 Ⅲ는 ‘인도네시아 영화의 르네상스’다.",
                       movieTitle: ["괴물", "녹야", "더 비스트"],
                       movieEng: ["Monster", "Green Night", "The Beast"],
                       directorNm: ["고레에다 히로카즈", "한슈아이", "베르트랑 보넬로"],
                       directorEng: ["KORE-EDA Hirokazu", "HAN Shuai", "Bertrand BONELLO"],
                       runningTime: [126, 92, 146]),
        Classification(id: 23,
                       title: "특별상영",
                       description: "2023 부산국제영화제 특별상영작",
                       movieTitle: ["괴물", "녹야", "더 비스트"],
                       movieEng: ["Monster", "Green Night", "The Beast"],
                       directorNm: ["고레에다 히로카즈", "한슈아이", "베르트랑 보넬로"],
                       directorEng: ["KORE-EDA Hirokazu", "HAN Shuai", "Bertrand BONELLO"],
                       runningTime: [126, 92, 146])
    ]
}
